Kubernetes networks #3
otus-kuber-2019-06/dbaskakov_platform pull request #4
Opened 2019-08-07 09:47 UTC by dbaskakov

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [ ] Задание со * (канарейка не взлетела )

## В процессе сделано:
1. Добавление проверок Pod
2. Создание объекта Deployment
3. Добавление сервисов в кластер ( ClusterIP )
4. Включение режима балансировки IPVS

## Как проверить работоспособность:
 - DNS. применить манифест dns-svc-lb.yaml.  сделать dig
 - dashboard. применить манифест dashboard-ingress.yaml. Дашборд должен открыться по адресу http://ip/dashboard
 - при добавлении аннотации nginx.ingress.kubernetes.io/canary: "true" доступ через ингресс 
   через ингресс не работал

 

## PR checklist:
 - [x] Выставлен label с номером домашнего задания

2019-08-07 09:48 UTC, dbaskakov commented
@virtualshuric может подскажешь , почему перестает работать после добавления аннотации 
nginx.ingress.kubernetes.io/canary: "true"

2019-08-07 10:25 UTC, virtualshuric commented
ДЗ проверено, все хорошо, кроме известных проблем (см. комментарии). Если хочется добить "канарейку", могу пока не мерджить.

2019-08-07 10:29 UTC, dbaskakov commented
> ДЗ проверено, все хорошо, кроме известных проблем (см. комментарии). Если хочется добить "канарейку", могу пока не мерджить.
Прошу пока не мерджить, хочется еще немного поковырять канарейку
А в какие именно комментарии смотреть ? :)

2019-08-07 10:34 UTC, virtualshuric requested changes
> > ДЗ проверено, все хорошо, кроме известных проблем (см. комментарии). Если хочется добить "канарейку", могу пока не мерджить.
> > Прошу пока не мерджить, хочется еще немного поковырять канарейку
> > А в какие именно комментарии смотреть ? :)

Можно пройтись здесь по вкладке Conversation или пролистать файлики на вкладке Changed files - я там сделал пометки.
Я переношу тогда карточку в "Отправлено на доработку", как будет готово - можно ставить Label `review required`, переоткрывать PR не надо

2019-08-07 10:34 UTC, virtualshuric commented on kubernetes-networks/canary/canary-deployment.yaml
> +apiVersion: extensions/v1beta1
Лучше использовать apiVersion `apps/v1`. Иначе, с версии 1.16 этот манифест перестанет работать

2019-08-07 10:34 UTC, virtualshuric commented on kubernetes-networks/dashboard-ingress.yaml
> +apiVersion: extensions/v1beta1
Актуальная apiVersion для ингресс-ресурсов - `networking.k8s.io/v1beta1`

2019-08-07 10:34 UTC, virtualshuric commented on kubernetes-networks/web-deploy.yaml
> +         limits:
То, что выставлены лимиты ресурсов для Pod - очень хорошо!

2019-08-07 10:34 UTC, virtualshuric commented on kubernetes-networks/canary/canary-config.yaml
> +apiVersion: v1
Хорошее решение - использовать ConfigMap для настройки пода с nginxом! 👍

2019-08-07 10:34 UTC, virtualshuric commented on kubernetes-networks/canary/canary-deployment.yaml
> +              path: /
Делать идентичную liveness/readiness probe - не стоит. У них немного разные задачи. А в случае с веб-сервером, не уверен что стоит рестартовать контейнер, если nginx вернул 403/404 ошибку (или 500/502, как это часто на фронтах бывает). Для ДЗ - ок, пусть будет )

2019-08-07 10:34 UTC, virtualshuric commented on kubernetes-networks/canary/canary-ingress.yaml
> +      nginx.ingress.kubernetes.io/canary: "true"
Проблема с канарейкой в данном случае в том, что когда есть эта аннотация, то ingress-контроллер ищет подходящий основной сервис, к которому надо прикрутить эту  canary-конфигурацию. И если не находит, то игнорирует этот ingress-ресурс. В данном случае, чтобы заработало - нужно два ingress-ресурса, с одинаковыми host/path в правилах роутинга (т.е оба должны ссылаться или на canary.softpro.site/, или на express.softpro.site/). Тогда контроллер оба ресурса обработает и начнет размазывать трафик между основным и canary-бэкендом. Кстати, в условиях ДЗ нужна была не просто "канарейка", а канарейка с маршрутизацией по HTTP-заголовку (это еще 1-2 аннотации в ингрессе).

2019-08-08 11:43 UTC, virtualshuric approved these changes
Теперь все хорошо, ДЗ принято!

2019-08-08 11:44 UTC, merged